services:
  task-app:
    image: ghcr.io/jacobdvorsky-del/github_actions_practice/tasks_app:${IMAGE_TAG:-latest}
    restart: unless-stopped
    container_name: task-app
    ports:
      - "50090:5000"