# Merge to main → build image → push to GHCR → deploy staging → verify → approve → deploy production.
name: CD - on main Push
on:
  push:
    branches: ['main']

permissions:
  contents: read
  packages: write

concurrency: 
  group: cd-${{ github.ref }}
  cancel-in-progress: false 

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Set lowercase repo
        id: repo
        run: echo "name=${GITHUB_REPOSITORY@L}" >> "$GITHUB_OUTPUT"
      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: | 
            ${{ vars.GHCR_PATH }}/${{ vars.APP_NAME }}:latest
            ${{ vars.GHCR_PATH }}/${{ vars.APP_NAME }}:${{ github.sha }}

  deploy-staging: # Refactor later
    name: Deploy on Staging # Is getting docker compose from docker sensitive for changes ? 
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - build-and-push
    environment: Staging
    steps:
      - name: Execute ssh commands on Staging VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            docker pull ${{ vars.GHCR_PATH }}/${{ vars.APP_NAME }}:${{ github.sha }}
            docker compose -f https://github.com/jacobdvorsky-del/GitHub_Actions_Practice.git@${{ github.sha }} down || TRUE
            IMAGE_TAG=${{ github.sha }} docker compose -f https://github.com/jacobdvorsky-del/GitHub_Actions_Practice.git@${{ github.sha }} up -d
            sleep 4
            curl "http://localhost:50090/health"
        
            
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - deploy-staging
    environment: Staging
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14' # Add python version to variable
      - name: Install dependencies
        run: pip install -r tests/requirements.txt
      - name: Run Tests
        run: pytest tests/tests -v --api-url "http://${{ secrets.AZURE_HOST }}:50090"

  #  Manual Approve before deploying on production
  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: tests
    environment: Production
    steps:
      - name: Execute ssh commands on Production VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            docker pull ${{ vars.GHCR_PATH }}/${{ vars.APP_NAME }}:${{ github.sha }}
            docker compose -f https://github.com/jacobdvorsky-del/GitHub_Actions_Practice.git@${{ github.sha }} down || TRUE
            IMAGE_TAG=${{ github.sha }} docker compose -f https://github.com/jacobdvorsky-del/GitHub_Actions_Practice.git@${{ github.sha }} up -d
            sleep 4
            curl "http://localhost:50090/health"
      
    
